### ISSUE TITLE
Enable pre_ping on pool

### ISSUE THREAD

**Issue by edevil** [lcd1232/django-postgrespool2#3]
I was trying to enable "pre_ping" on the sqlalchemy pool to better deal with dead connections but I seem to be having problems choosing the right dialect class.

These are the options I'm currently using:

```
from sqlalchemy.dialects import postgresql
DATABASE_POOL_ARGS = {
    'max_overflow': 0,
    'pool_size': 3,
    'recycle': 3600,
    'timeout': 10,
    'pre_ping': True,
    'dialect': postgresql.dialect(),
}
```

However when I start Django I get an error while enable autocommit:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10dcb12f0>
Traceback (most recent call last):
  File "//anaconda/envs/opp/lib/python3.6/site-packages/django_postgrespool2/base.py", line 118, in _set_autocommit
    self.connection.connection.autocommit = autocommit
psycopg2.ProgrammingError: set_session cannot be used inside a transaction
```

Am I doing something wrong or is "pre_ping" not supported at the moment?

**Comment by lcd1232** [comment]
@edevil it seems like you have problem as described [here](https://github.com/dbcli/pgcli/issues/646). Could you say what psycopg2 version do you use? Try to check this issue with **psycopg2==2.6.2**

**Comment by edevil** [comment]
Yes, it is related to the initial "select()" done by ```pre_ping```. I think I address it correctly in #4.

**Comment by edevil** [comment]
@lcd1232 Maybe it's time for "0.2.0 - END 2017"? :)
