### ISSUE TITLE
Support Postgis?

### ISSUE THREAD

**Issue by lzambrano18** [lcd1232/django-postgrespool2#7]
Hello, I tried to run the project with the Postgis backend but this error occurs

` django.core.exceptions.ImproperlyConfigured: 'django_postgrespool2.postgis' isn't an available database backend.
       | Try using 'django.db.backends.XXX', where XXX is one of:
       |     'mysql', 'oracle', 'postgresql', 'sqlite3'
       | Error was: No module named postgis.base
`
any solution?

**Comment by lcd1232** [comment]
@lzambrano18 postgis backend will be available in release 0.2.0. I think I will make it in 2-3 days. Right now you can try to use master branch, it should works:
`$ pip install git+git://github.com/lcd1232/django-postgrespool2.git@master`

**Comment by matthewh** [comment]
Hello @lcd1232, when do you think the release with postgis support will be available?

**Comment by lcd1232** [comment]
@matthewh it is available since version 0.2.0
`$ pip install "django_postgrespool2>=0.2.0"`

**Comment by fdemmer** [comment]
the package you pushed to pypi as 0.2.0 does not contain the postgis code.

**Comment by andrewtmendoza** [comment]
@lcd1232 is this issue still open?

**Comment by lcd1232** [comment]
No, PostGIS is available at pypi
